// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztruuuuipxnzdolqirwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0cnV1dXVpcHhuemRvbHFpcnduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NzU0NzYsImV4cCI6MjA1OTI1MTQ3Nn0.rm7q3-QZOWVLGF8xPn_wgQOJjf2qbJ0JYTdF78jwXRY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);